### ISSUE TITLE
Write this week's report

### ISSUE THREAD

**Issue by ins305** [SE-TINF22B6/Statify#2]
• This week’s report/blog (use GitHub Discussion) should cover:
1. Introduction of your team, including the major role(s) for each team
member. Example (not necessary to be a table):
https://moodle.dhbw.de/pluginfile.php/294999/mod_resource/content/0/02%20Tasks%20setup%20scrum.pdf
2. Vision of your project
3. Techniques/platforms plan to be used
4. Scrum setup: platform to use, Sprint length, etc.
5. Sprint 1 backlog
6. Post a screenshot of your Kanban
• Leave some buffer time for others to review your blog!

**Comment by kingGiter** [comment]
[Statify.docx](https://github.com/SE-TINF22B6/Statify/files/13033567/Statify.docx)
